config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :users
  
  get "/grocery_list", to: "home#get_grocery_list"
  get "/ingredients_list", to: "home#get_ingredients_list"

  get '/signup', to: "users#new"
  post '/signup', to: "users#create"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  root to: "sessions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredient
  has_many :recipes, through: :recipe_ingredient

  validates :name, :unit, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredient
  has_many :ingredients, through: :recipe_ingredient

  validates :link, presence: true
  validates :name, presence: true
  validate :can_only_be_favorited_if_approved

  def can_only_be_favorited_if_approved
    if is_favorited && status != "approved"
        errors[:favorited] << "Can only be favorited if recipe is approved."
    end
  end

  enum status: [:pending, :approved, :rejected]
  
  after_initialize :set_defaults
  def set_defaults
    default_recipe_imgs = [
      "https://lets-eat-imgs.s3.amazonaws.com/recipe_1.jpg",
      "https://lets-eat-imgs.s3.amazonaws.com/recipe_2.png",
      "https://lets-eat-imgs.s3.amazonaws.com/recipe_3.jpeg",
      "https://lets-eat-imgs.s3.amazonaws.com/recipe_4.jpeg",
      "https://lets-eat-imgs.s3.amazonaws.com/recipe_5.jpeg",
    ]
    
    if !self.img_url || self.img_url == "" || self.img_url == " "
      self.img_url = default_recipe_imgs.sample
    end
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient

  validates :count, numericality: {greater_than: 0}, presence: true
  validates :recipe_id, :ingredient_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes

  has_secure_password
  
  validates :username, :presence => true
  validates :username, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception 
 
  def current_user 
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id] 
  end 
  helper_method :current_user 

  def authenticate_user! 
   redirect_to ‘/login’ unless current_user 
  end 

end

app/controllers/home_controller.rb
require 'pry'

class HomeController < ApplicationController
  def get_grocery_list
    weekly_recipes = Recipe.where("'#{Date.parse(params[:week])}' = ANY (weeks)")
    weekly_ingredients = []
    weekly_recipes.each do |recipe|
      get_ingredients_by_recipe_id(weekly_ingredients, recipe.id)
    end
    @grocery_list = {}
    weekly_ingredients.each do |weekly_ingredient|
      if @grocery_list[weekly_ingredient[:name]]
        ingredient_counts_units = @grocery_list[weekly_ingredient[:name]]
        ingredient_counts_units.each do |counts_unit| 
          if counts_unit[:unit] == weekly_ingredient[:unit]
            counts_unit[:count] += weekly_ingredient[:count]
          else
            @grocery_list[weekly_ingredient[:name]] << {count: weekly_ingredient[:count], unit: weekly_ingredient[:unit]}
          end
        end
      else
        @grocery_list[weekly_ingredient[:name]] = [{count: weekly_ingredient[:count], unit: weekly_ingredient[:unit]}]
      end
    end
  end

  def get_ingredients_by_recipe_id(ingredients_arr, recipe_id)
    recipe_ingredients = RecipeIngredient.where(recipe_id: recipe_id)
    recipe_ingredients.each do |recipe_ingredient|
      ing = Ingredient.find(recipe_ingredient.ingredient_id)
      ingredients_arr << {
        count: recipe_ingredient[:count],
        unit: ing[:unit],
        name: ing[:name]
      }
    end
    ingredients_arr
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
  end

  def create
  end

  def update
  end

  def delete
  end
end

app/controllers/recipes_controller.rb
require 'pry'
class RecipesController < ApplicationController
  def index
    if current_user
      @recipes = Recipe.order(:id)
      render "index"
    else
      render 'sessions/new'
    end
    # render json: {recipes: recipes}, status: 200
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
    @ingredients = []
    recipe_ingredients = RecipeIngredient.where(recipe_id: params[:id])
    recipe_ingredients.each do |recipe_ingredient|
      ing = Ingredient.find(recipe_ingredient.ingredient_id)
      @ingredients << {
        count: recipe_ingredient[:count],
        unit: ing[:unit],
        name: ing[:name]
      }
    end
  end

  def create
    user = User.find(params[:user_id])
    @recipe = user.recipes.create(recipe_params.except(:ingredients))
    redirect_to recipe_path(@recipe)
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe
        update_recipe_ingredients(@recipe, recipe_params[:ingredients]) if recipe_params[:ingredients]
        if @recipe.update(recipe_params.except(:ingredients))
          redirect_to recipe_path(@recipe), status: 302
        else
          flash[:alert] = 'unable to update recipe'
          render :edit, status: 400
        end
    else
      render json: {error: "unable to update recipe, recipe could not be found"}, status: 400
    end
  end

  def destroy
    binding.pry
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_path, status: 300
  end

  private
    def recipe_params
      params.require(:recipe).permit(:id, :name, :link, :status, :notes, :user_id, :img_url, :is_favorited, {ingredients: [:name, :count, :unit]}, {weeks: []})
    end

    def format_ingredient(ingredient, recipe_id)
      {
        name: ingredient.name,
        unit: ingredient.unit,
        count: RecipeIngredient.where(
          ingredient_id: ingredient.id,
          recipe_id: recipe_id
        ).count
      }
    end

    def update_recipe_ingredients(recipe, new_ingredients)
      old_ingredients = RecipeIngredient.where({"recipe_id" => recipe[:id]})
      remove_ingredients(new_ingredients, old_ingredients)
      add_ingredients(new_ingredients, old_ingredients, recipe[:id])
    end

    def remove_ingredients(new_ingredients, old_ingredients)
      old_ingredients.each do |old_ingredient|
        unless new_ingredients.include?(old_ingredient)
          old_ingredient.destroy!
        end
      end
    end

    def add_ingredients(new_ingredients, old_ingredients, recipe_id)
      new_ingredients.each do |ingredient|
        unless old_ingredients.include?(ingredient)
          new_ingredient = Ingredient.find_or_create_by({"name"=> ingredient[:name], "unit" => ingredient[:unit]})
          if new_ingredient.valid?
            recipe_ingredient = RecipeIngredient.find_or_create_by({
              "recipe_id"=> recipe_id,
              "ingredient_id"=> new_ingredient[:id]
            })
            if recipe_ingredient[:count] && ingredient[:count]
              ing_count = recipe_ingredient[:count].to_i + ingredient[:count].to_i
            else
              ing_count = 1
            end
            recipe_ingredient.update(:count => ing_count)
          end
        end
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: login_params[:username])
    if user && user.authenticate(login_params[:password])
      session[:user_id] = user.id
      redirect_to recipes_path, status: 302
    else
      flash[:alert] = "invalid username or password"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, status: 302
  end

  private
    def login_params
      params.permit(:authenticity_token, :commit, :username, :password)
    end
end

app/controllers/users_controller.rb
require 'pry'
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to recipes_path, status: 300
    else
      render "new"
    end
  end

  private
    def user_params
      params.permit(:authenticity_token, :commit, :user => [:username, :password, :password_confirmation])
    end
end 

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lets Eat</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/edit.html.haml
%h2 edit recipe
=form_with model: @recipe do |form|
  .name
    =form.label :name
    %br
    =form.text_field :name
    %br
  .link
    =form.label :link
    %br
    =form.text_field :link
    %br
  .img_url
    =form.label :img_url
    %br
    =form.text_field :img_url
    %br
  .notes
    =form.label :notes
    %br
    =form.text_field :notes
    %br
  =form.submit
  
=link_to 'back', recipes_path

app/views/recipes/index.html.haml
%h2 recipes
=link_to 'new recipe', new_recipe_path
%br
=link_to 'logout', logout_path
#index_grid
  -@recipes.each do |recipe|
    .card
      %strong= recipe.name
      =link_to 'view', recipe
      %br
      =image_tag recipe.img_url, class: "recipe_img"
      %br
      %i= "submitted by: #{recipe.user.username}"

    %br

app/views/recipes/new.html.haml
%h2 new recipe

=form_with model: @recipe do |form|
  .name
    =form.label :name
    %br
    =form.text_field :name
    %br
    -@recipe.errors.full_messages_for(:name).each do |msg|
      %p= msg
  .link
    =form.label :link
    %br
    =form.text_field :link
    %br
    -@recipe.errors.full_messages_for(:link).each do |msg|
      %p= msg
  .img_url
    =form.label :img_url
    %br
    =form.text_field :img_url
    %br
    -@recipe.errors.full_messages_for(:img_url).each do |msg|
      %p= msg
  .notes
    =form.label :notes
    %br
    =form.text_field :notes
    %br
    -@recipe.errors.full_messages_for(:notes).each do |msg|
      %p= msg
  =hidden_field(:user_id, @user.id)
  =form.submit
  
=link_to 'back', root_url

app/views/recipes/show.html.haml
%h2= @recipe.name
=image_tag @recipe.img_url, class: "recipe_img"
%br
=link_to 'visit recipe', @recipe.link
%br
%p= @recipe.notes
.ingredients
  %h4 ingredients
  %ul
    -@ingredients.each do |ingredient|
      %li= "#{ingredient[:name]}: #{ingredient[:count]} #{ingredient[:unit]}"
%i= "submitted by #{@recipe.user.username}"
%br
=link_to 'edit recipe', edit_recipe_path(@recipe)
%br
=link_to 'delete recipe', recipe_path(@recipe), data: {turbo_method: :delete, turbo_confirm: "are you sure?"}

%br
=link_to 'back', root_path

app/views/users/new.html.haml
%h2 create account
=form_with model: @user do |form|
  .username
    =form.label :username
    %br
    =form.text_field :username
    %br
  .password
    =form.label :password
    %br
    =form.password_field :password
    %br
  .name
    =form.label :password_confirmation
    %br
    =form.password_field :password_confirmation
    %br
  =form.submit
=link_to 'back', login_path